micronaut:
  application:
    name: example-jobrunr-micronaut
  metrics:
    enabled: true

#datasources:
#  default:
#    url: jdbc:h2:file:/tmp/default
#    driverClassName: org.h2.Driver

#mongodb:
#  servers.*.uuid-representation: STANDARD
#  uri: mongodb://127.0.0.1:27017/jobrunr

#redis:
#  uri: redis://localhost

#elasticsearch:
#  httpHosts: http://127.0.0.1:9200

jobrunr:
  job-scheduler:
    enabled: true
  background-job-server:
    enabled: true
  dashboard:
    enabled: true

endpoints:
  health:
    enabled: true
    details-visible: anonymous
  metrics:
    enabled: true
    sensitive: false

myjob:
  cron: "*/15 * * * *"